const places = [
  { name: 'Aberdeen Falls', location: 'Nuwara Eliya, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Abhayagiri', location: 'Anuradhapura, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Adam\'s Peak', location: 'Nuwara Eliya/Rathnapura, Sri Lanka', categories: ['adventure', 'mountains'], image: 'Images/.jpg' },
  { name: 'Alakola Ella', location: 'Kandy, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Arugam Bay', location: 'Ampara District, Sri Lanka', categories: ['adventure'], image: 'Images/.jpg' },
  { name: 'Arugam Bay Beach', location: 'Ampara, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Baker\'s Falls', location: 'Horton Plains, Nuwara Eliya, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Bambarakanda Falls', location: 'Badulla, Sri Lanka', categories: ['adventure', 'waterfalls'], image: 'Images/.jpg' },
  { name: 'Batalegala', location: 'Kegalle, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Belihuloya', location: 'Ratnapura District, Sri Lanka', categories: ['adventure'], image: 'Images/.jpg' },
  { name: 'Bentota Beach', location: 'Galle, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Bible Rock', location: 'Kegalle, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Bomburu Ella', location: 'Nuwara Eliya, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Bopath Ella', location: 'Ratnapura, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Bundala National Park', location: 'Hambantota, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Casuarina Beach', location: 'Jaffna, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Dambulla Cave Temple', location: 'Dambulla, Matale District, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Devon Falls', location: 'Nuwara Eliya, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Diyaluma Falls', location: 'Badulla, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Diyaluma Falls Upper Pools', location: 'Badulla District, Sri Lanka', categories: ['adventure'], image: 'Images/.jpg' },
  { name: 'Dolukanda', location: 'Kurunegala, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Dunhinda Falls', location: 'Badulla, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Ella Rock', location: 'Ella, Badulla, Sri Lanka', categories: ['adventure', 'mountains'], image: 'Images/.jpg' },
  { name: 'Embekke Devalaya', location: 'Udunuwara, Kandy District, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Gal Oya National Park', location: 'Ampara, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Gal Vihara', location: 'Polonnaruwa, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Galboda Falls', location: 'Nuwara Eliya, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Galle Fort', location: 'Galle, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Hanthana Mountain Range', location: 'Kandy, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Hikkaduwa Marine National Park', location: 'Hikkaduwa, Galle District, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Hiriketiya Beach', location: 'Matara, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Horton Plains National Park', location: 'Nuwara Eliya District, Sri Lanka', categories: ['adventure', 'wildlife'], image: 'Images/.jpg' },
  { name: 'Jaya Sri Maha Bodhi', location: 'Anuradhapura, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Jetavanaramaya', location: 'Anuradhapura, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Jungle Beach', location: 'Galle, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Kalpitiya', location: 'Puttalam District, Sri Lanka', categories: ['adventure'], image: 'Images/.jpg' },
  { name: 'Kalpitiya Beach', location: 'Puttalam, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Kaudulla National Park', location: 'Polonnaruwa, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Kelaniya Raja Maha Vihara', location: 'Kelaniya, Gampaha District, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Kirigalpoththa', location: 'Horton Plains, Nuwara Eliya, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Kirindi Ella Falls', location: 'Ratnapura, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Kitulgala', location: 'Kegalle District, Sri Lanka', categories: ['adventure'], image: 'Images/.jpg' },
  { name: 'Knuckles Mountain Range', location: 'Matale/Kandy, Sri Lanka', categories: ['adventure', 'mountains'], image: 'Images/.jpg' },
  { name: 'Kuda Oya Falls', location: 'Monaragala, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Kumana National Park', location: 'Ampara, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Lanka Ella Falls', location: 'Ella, Badulla, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Lankatilaka Temple', location: 'Hiyarapitiya, Kandy District, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Laxapana Falls', location: 'Nuwara Eliya, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Little Adam\'s Peak', location: 'Ella, Badulla, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Lunugamvehera National Park', location: 'Hambantota, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Madulsima', location: 'Badulla District, Sri Lanka', categories: ['adventure'], image: 'Images/.jpg' },
  { name: 'Maduru Oya National Park', location: 'Ampara / Polonnaruwa, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Manawela Falls', location: 'Kandy, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Meemure', location: 'Meemure, Kandy District, Sri Lanka', categories: ['adventure'], image: 'Images/.jpg' },
  { name: 'Mihintale', location: 'Mihintale, Anuradhapura District, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Minneriya National Park', location: 'Polonnaruwa, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Mirissa Beach', location: 'Matara, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Mount Lavinia Beach', location: 'Colombo, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Namunukula', location: 'Badulla, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Nilaveli Beach', location: 'Trincomalee, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Pahanthudawa Falls', location: 'Ratnapura, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Passikudah Beach', location: 'Batticaloa, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Pidurangala Rock', location: 'Matale, Sri Lanka', categories: ['adventure', 'mountains'], image: 'Images/.jpg' },
  { name: 'Pigeon Island National Park', location: 'Nilaveli, Trincomalee District, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Polhena Beach', location: 'Matara, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Polonnaruwa Vatadage', location: 'Polonnaruwa, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Ramboda Falls', location: 'Nuwara Eliya, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Ravana Falls', location: 'Ella, Badulla, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Riverston', location: 'Matale District, Sri Lanka', categories: ['adventure'], image: 'Images/.jpg' },
  { name: 'Ruwanwelisaya', location: 'Anuradhapura, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Sera Ella Falls', location: 'Matale, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Sigiriya', location: 'Sigiriya, Matale District, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Sigiriya Rock', location: 'Matale, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Single Tree Hill', location: 'Nuwara Eliya, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Sinharaja Forest Reserve', location: 'Ratnapura, Galle & Matara Districts, Sri Lanka', categories: ['adventure', 'wildlife'], image: 'Images/.jpg' },
  { name: 'St. Clair\'s Falls', location: 'Nuwara Eliya, Sri Lanka', categories: ['waterfalls'], image: 'Images/.jpg' },
  { name: 'Talalla Beach', location: 'Matara, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Tangalle Beach', location: 'Hambantota, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Temple of the Sacred Tooth Relic', location: 'Kandy, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
  { name: 'Totapola Kanda', location: 'Horton Plains, Nuwara Eliya, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Udawalawe National Park', location: 'Ratnapura / Hambantota, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Unawatuna Beach', location: 'Galle, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Uppuveli Beach', location: 'Trincomalee, Sri Lanka', categories: ['beaches'], image: 'Images/.jpg' },
  { name: 'Wasgamuwa National Park', location: 'Matale / Polonnaruwa, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Wilpattu National Park', location: 'Puttalam / Anuradhapura, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'World\'s End', location: 'Horton Plains, Nuwara Eliya, Sri Lanka', categories: ['mountains'], image: 'Images/.jpg' },
  { name: 'Yala National Park', location: 'Hambantota / Monaragala, Sri Lanka', categories: ['wildlife'], image: 'Images/.jpg' },
  { name: 'Yapahuwa', location: 'Yapahuwa, Kurunegala District, Sri Lanka', categories: ['culture'], image: 'Images/.jpg' },
];